/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountEvent

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param events 
 * @param nextFrom 
 */
@Serializable

data class AccountEvents (

    @SerialName(value = "events")
    val events: kotlin.collections.List<AccountEvent>,

    @SerialName(value = "next_from")
    val nextFrom: kotlin.Long

)

