/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param usedCells 
 * @param usedBits 
 * @param usedPublicCells 
 * @param lastPaid time of the last payment
 * @param duePayment 
 */
@Serializable

data class AccountStorageInfo (

    @SerialName(value = "used_cells")
    val usedCells: kotlin.Long,

    @SerialName(value = "used_bits")
    val usedBits: kotlin.Long,

    @SerialName(value = "used_public_cells")
    val usedPublicCells: kotlin.Long,

    /* time of the last payment */
    @SerialName(value = "last_paid")
    val lastPaid: kotlin.Long,

    @SerialName(value = "due_payment")
    val duePayment: kotlin.Long

)

