/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * Values: unchanged,frozen,deleted
 */
@Serializable
enum class AccStatusChange(val value: kotlin.String) {

    @SerialName(value = "acst_unchanged")
    unchanged("acst_unchanged"),

    @SerialName(value = "acst_frozen")
    frozen("acst_frozen"),

    @SerialName(value = "acst_deleted")
    deleted("acst_deleted");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AccStatusChange) "$data" else null

        /**
         * Returns a valid [AccStatusChange] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AccStatusChange? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

