/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param success 
 * @param resultCode 
 * @param totalActions 
 * @param skippedActions 
 * @param fwdFees 
 * @param totalFees 
 * @param resultCodeDescription 
 */
@Serializable

data class ActionPhase (

    @SerialName(value = "success")
    val success: kotlin.Boolean,

    @SerialName(value = "result_code")
    val resultCode: kotlin.Int,

    @SerialName(value = "total_actions")
    val totalActions: kotlin.Int,

    @SerialName(value = "skipped_actions")
    val skippedActions: kotlin.Int,

    @SerialName(value = "fwd_fees")
    val fwdFees: kotlin.Long,

    @SerialName(value = "total_fees")
    val totalFees: kotlin.Long,

    @SerialName(value = "result_code_description")
    val resultCodeDescription: kotlin.String? = null

)

