/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.ActionSimplePreview
import io.tonapi.models.AuctionBidAction
import io.tonapi.models.ContractDeployAction
import io.tonapi.models.DepositStakeAction
import io.tonapi.models.DomainRenewAction
import io.tonapi.models.ElectionsDepositStakeAction
import io.tonapi.models.ElectionsRecoverStakeAction
import io.tonapi.models.InscriptionMintAction
import io.tonapi.models.InscriptionTransferAction
import io.tonapi.models.JettonBurnAction
import io.tonapi.models.JettonMintAction
import io.tonapi.models.JettonSwapAction
import io.tonapi.models.JettonTransferAction
import io.tonapi.models.NftItemTransferAction
import io.tonapi.models.NftPurchaseAction
import io.tonapi.models.SmartContractAction
import io.tonapi.models.SubscriptionAction
import io.tonapi.models.TonTransferAction
import io.tonapi.models.UnSubscriptionAction
import io.tonapi.models.WithdrawStakeAction
import io.tonapi.models.WithdrawStakeRequestAction

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param status 
 * @param simplePreview 
 * @param baseTransactions 
 * @param tonTransfer 
 * @param contractDeploy 
 * @param jettonTransfer 
 * @param jettonBurn 
 * @param jettonMint 
 * @param nftItemTransfer 
 * @param subscribe 
 * @param unSubscribe 
 * @param auctionBid 
 * @param nftPurchase 
 * @param depositStake 
 * @param withdrawStake 
 * @param withdrawStakeRequest 
 * @param electionsDepositStake 
 * @param electionsRecoverStake 
 * @param jettonSwap 
 * @param smartContractExec 
 * @param domainRenew 
 * @param inscriptionTransfer 
 * @param inscriptionMint 
 */
@Serializable

data class Action (

    @SerialName(value = "type")
    val type: Action.Type,

    @SerialName(value = "status")
    val status: Action.Status,

    @SerialName(value = "simple_preview")
    val simplePreview: ActionSimplePreview,

    @SerialName(value = "base_transactions")
    val baseTransactions: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "TonTransfer")
    val tonTransfer: TonTransferAction? = null,

    @SerialName(value = "ContractDeploy")
    val contractDeploy: ContractDeployAction? = null,

    @SerialName(value = "JettonTransfer")
    val jettonTransfer: JettonTransferAction? = null,

    @SerialName(value = "JettonBurn")
    val jettonBurn: JettonBurnAction? = null,

    @SerialName(value = "JettonMint")
    val jettonMint: JettonMintAction? = null,

    @SerialName(value = "NftItemTransfer")
    val nftItemTransfer: NftItemTransferAction? = null,

    @SerialName(value = "Subscribe")
    val subscribe: SubscriptionAction? = null,

    @SerialName(value = "UnSubscribe")
    val unSubscribe: UnSubscriptionAction? = null,

    @SerialName(value = "AuctionBid")
    val auctionBid: AuctionBidAction? = null,

    @SerialName(value = "NftPurchase")
    val nftPurchase: NftPurchaseAction? = null,

    @SerialName(value = "DepositStake")
    val depositStake: DepositStakeAction? = null,

    @SerialName(value = "WithdrawStake")
    val withdrawStake: WithdrawStakeAction? = null,

    @SerialName(value = "WithdrawStakeRequest")
    val withdrawStakeRequest: WithdrawStakeRequestAction? = null,

    @SerialName(value = "ElectionsDepositStake")
    val electionsDepositStake: ElectionsDepositStakeAction? = null,

    @SerialName(value = "ElectionsRecoverStake")
    val electionsRecoverStake: ElectionsRecoverStakeAction? = null,

    @SerialName(value = "JettonSwap")
    val jettonSwap: JettonSwapAction? = null,

    @SerialName(value = "SmartContractExec")
    val smartContractExec: SmartContractAction? = null,

    @SerialName(value = "DomainRenew")
    val domainRenew: DomainRenewAction? = null,

    @SerialName(value = "InscriptionTransfer")
    val inscriptionTransfer: InscriptionTransferAction? = null,

    @SerialName(value = "InscriptionMint")
    val inscriptionMint: InscriptionMintAction? = null

) {

    /**
     * 
     *
     * Values: tonTransfer,jettonTransfer,jettonBurn,jettonMint,nftItemTransfer,contractDeploy,subscribe,unSubscribe,auctionBid,nftPurchase,depositStake,withdrawStake,withdrawStakeRequest,jettonSwap,smartContractExec,electionsRecoverStake,electionsDepositStake,domainRenew,inscriptionTransfer,inscriptionMint,unknown
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "TonTransfer") tonTransfer("TonTransfer"),
        @SerialName(value = "JettonTransfer") jettonTransfer("JettonTransfer"),
        @SerialName(value = "JettonBurn") jettonBurn("JettonBurn"),
        @SerialName(value = "JettonMint") jettonMint("JettonMint"),
        @SerialName(value = "NftItemTransfer") nftItemTransfer("NftItemTransfer"),
        @SerialName(value = "ContractDeploy") contractDeploy("ContractDeploy"),
        @SerialName(value = "Subscribe") subscribe("Subscribe"),
        @SerialName(value = "UnSubscribe") unSubscribe("UnSubscribe"),
        @SerialName(value = "AuctionBid") auctionBid("AuctionBid"),
        @SerialName(value = "NftPurchase") nftPurchase("NftPurchase"),
        @SerialName(value = "DepositStake") depositStake("DepositStake"),
        @SerialName(value = "WithdrawStake") withdrawStake("WithdrawStake"),
        @SerialName(value = "WithdrawStakeRequest") withdrawStakeRequest("WithdrawStakeRequest"),
        @SerialName(value = "JettonSwap") jettonSwap("JettonSwap"),
        @SerialName(value = "SmartContractExec") smartContractExec("SmartContractExec"),
        @SerialName(value = "ElectionsRecoverStake") electionsRecoverStake("ElectionsRecoverStake"),
        @SerialName(value = "ElectionsDepositStake") electionsDepositStake("ElectionsDepositStake"),
        @SerialName(value = "DomainRenew") domainRenew("DomainRenew"),
        @SerialName(value = "InscriptionTransfer") inscriptionTransfer("InscriptionTransfer"),
        @SerialName(value = "InscriptionMint") inscriptionMint("InscriptionMint"),
        @SerialName(value = "Unknown") unknown("Unknown");
    }
    /**
     * 
     *
     * Values: ok,failed
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "ok") ok("ok"),
        @SerialName(value = "failed") failed("failed");
    }
}

