/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * shortly describes what this action is about.
 *
 * @param name 
 * @param description 
 * @param accounts 
 * @param actionImage a link to an image for this particular action.
 * @param `value` 
 * @param valueImage a link to an image that depicts this action's asset.
 */
@Serializable

data class ActionSimplePreview (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String,

    @SerialName(value = "accounts")
    val accounts: kotlin.collections.List<AccountAddress>,

    /* a link to an image for this particular action. */
    @SerialName(value = "action_image")
    val actionImage: kotlin.String? = null,

    @SerialName(value = "value")
    val `value`: kotlin.String? = null,

    /* a link to an image that depicts this action's asset. */
    @SerialName(value = "value_image")
    val valueImage: kotlin.String? = null

)

