/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param b64 
 * @param b64url 
 */
@Serializable

data class AddressParse200ResponseBounceable (

    @SerialName(value = "b64")
    val b64: kotlin.String,

    @SerialName(value = "b64url")
    val b64url: kotlin.String

)

