/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.NftItem
import io.tonapi.models.Price

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param auctionType 
 * @param amount 
 * @param bidder 
 * @param auction 
 * @param nft 
 */
@Serializable

data class AuctionBidAction (

    @SerialName(value = "auction_type")
    val auctionType: AuctionBidAction.AuctionType,

    @SerialName(value = "amount")
    val amount: Price,

    @SerialName(value = "bidder")
    val bidder: AccountAddress,

    @SerialName(value = "auction")
    val auction: AccountAddress,

    @SerialName(value = "nft")
    val nft: NftItem? = null

) {

    /**
     * 
     *
     * Values: dNSPeriodTon,dNSPeriodTg,nUMBERPeriodTg,getgems
     */
    @Serializable
    enum class AuctionType(val value: kotlin.String) {
        @SerialName(value = "DNS.ton") dNSPeriodTon("DNS.ton"),
        @SerialName(value = "DNS.tg") dNSPeriodTg("DNS.tg"),
        @SerialName(value = "NUMBER.tg") nUMBERPeriodTg("NUMBER.tg"),
        @SerialName(value = "getgems") getgems("getgems");
    }
}

