/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param domain 
 * @param owner 
 * @param price 
 * @param bids 
 * @param date 
 */
@Serializable

data class Auction (

    @SerialName(value = "domain")
    val domain: kotlin.String,

    @SerialName(value = "owner")
    val owner: kotlin.String,

    @SerialName(value = "price")
    val price: kotlin.Long,

    @SerialName(value = "bids")
    val bids: kotlin.Long,

    @SerialName(value = "date")
    val date: kotlin.Long

)

