/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.GasLimitPrices

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The cost of computations in the basechains. The complexity of any computation is estimated in gas units.
 *
 * @param gasLimitsPrices 
 */
@Serializable

data class BlockchainConfig21 (

    @SerialName(value = "gas_limits_prices")
    val gasLimitsPrices: GasLimitPrices

)

