/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The configuration for the consensus protocol above catchain.
 *
 * @param fundamentalSmcAddr 
 */
@Serializable

data class BlockchainConfig31 (

    @SerialName(value = "fundamental_smc_addr")
    val fundamentalSmcAddr: kotlin.collections.List<kotlin.String>

)

