/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The limits on the number of validators in the TON blockchain.
 *
 * @param maxValidators 
 * @param maxMainValidators 
 * @param minValidators 
 */
@Serializable

data class BlockchainConfig16 (

    @SerialName(value = "max_validators")
    val maxValidators: kotlin.Int,

    @SerialName(value = "max_main_validators")
    val maxMainValidators: kotlin.Int,

    @SerialName(value = "min_validators")
    val minValidators: kotlin.Int

)

