/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * suspended accounts
 *
 * @param accounts 
 * @param suspendedUntil 
 */
@Serializable

data class BlockchainConfig44 (

    @SerialName(value = "accounts")
    val accounts: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "suspended_until")
    val suspendedUntil: kotlin.Int

)

