/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The network version and additional capabilities supported by the validators.
 *
 * @param version 
 * @param capabilities 
 */
@Serializable

data class BlockchainConfig8 (

    @SerialName(value = "version")
    val version: kotlin.Long,

    @SerialName(value = "capabilities")
    val capabilities: kotlin.Long

)

