/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Minting fees of new currencies.
 *
 * @param mintNewPrice 
 * @param mintAddPrice 
 */
@Serializable

data class BlockchainConfig6 (

    @SerialName(value = "mint_new_price")
    val mintNewPrice: kotlin.Long,

    @SerialName(value = "mint_add_price")
    val mintAddPrice: kotlin.Long

)

