/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.MsgForwardPrices

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The cost of sending messages in the basechains of the TON blockchain.
 *
 * @param msgForwardPrices 
 */
@Serializable

data class BlockchainConfig25 (

    @SerialName(value = "msg_forward_prices")
    val msgForwardPrices: MsgForwardPrices

)

