/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.BlockchainAccountInspectMethodsInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param code 
 * @param codeHash 
 * @param methods 
 * @param compiler 
 */
@Serializable

data class BlockchainAccountInspect (

    @SerialName(value = "code")
    val code: kotlin.String,

    @SerialName(value = "code_hash")
    val codeHash: kotlin.String,

    @SerialName(value = "methods")
    val methods: kotlin.collections.List<BlockchainAccountInspectMethodsInner>,

    @SerialName(value = "compiler")
    val compiler: BlockchainAccountInspect.Compiler? = null

) {

    /**
     * 
     *
     * Values: func
     */
    @Serializable
    enum class Compiler(val value: kotlin.String) {
        @SerialName(value = "func") func("func");
    }
}

