/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param currencyId 
 * @param amount 
 */
@Serializable

data class BlockchainConfig7CurrenciesInner (

    @SerialName(value = "currency_id")
    val currencyId: kotlin.Long,

    @SerialName(value = "amount")
    val amount: kotlin.String

)

