/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.JettonBridgeParams

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Bridge parameters for wrapping tokens from other networks into tokens on the TON network.
 *
 * @param jettonBridgeParams 
 */
@Serializable

data class BlockchainConfig79 (

    @SerialName(value = "jetton_bridge_params")
    val jettonBridgeParams: JettonBridgeParams

)

