/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param underload 
 * @param softLimit 
 * @param hardLimit 
 */
@Serializable

data class BlockParamLimits (

    @SerialName(value = "underload")
    val underload: kotlin.Long,

    @SerialName(value = "soft_limit")
    val softLimit: kotlin.Long,

    @SerialName(value = "hard_limit")
    val hardLimit: kotlin.Long

)

