/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.MisbehaviourPunishmentConfig

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The configuration for punishment for improper behavior (non-validation). In the absence of the parameter, the default fine size is 101 TON
 *
 * @param misbehaviourPunishmentConfig 
 */
@Serializable

data class BlockchainConfig40 (

    @SerialName(value = "misbehaviour_punishment_config")
    val misbehaviourPunishmentConfig: MisbehaviourPunishmentConfig

)

