/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.WorkchainDescr

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Workchains in the TON Blockchain
 *
 * @param workchains 
 */
@Serializable

data class BlockchainConfig12 (

    @SerialName(value = "workchains")
    val workchains: kotlin.collections.List<WorkchainDescr>

)

