/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.BlockchainConfig18StoragePricesInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The prices for data storage.
 *
 * @param storagePrices 
 */
@Serializable

data class BlockchainConfig18 (

    @SerialName(value = "storage_prices")
    val storagePrices: kotlin.collections.List<BlockchainConfig18StoragePricesInner>

)

