/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `public` 
 * @param root 
 */
@Serializable

data class BlockchainRawAccountLibrariesInner (

    @SerialName(value = "public")
    val `public`: kotlin.Boolean,

    @SerialName(value = "root")
    val root: kotlin.String

)

