/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.BlockchainBlock

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param lastKnownBlockId 
 * @param lastKnownBlock 
 */
@Serializable

data class BlockchainBlockShardsShardsInner (

    @SerialName(value = "last_known_block_id")
    val lastKnownBlockId: kotlin.String,

    @SerialName(value = "last_known_block")
    val lastKnownBlock: BlockchainBlock

)

