/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * List of mandatory parameters of the blockchain config.
 *
 * @param mandatoryParams 
 */
@Serializable

data class BlockchainConfig9 (

    @SerialName(value = "mandatory_params")
    val mandatoryParams: kotlin.collections.List<kotlin.Int>

)

