/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param utimeSince 
 * @param bitPricePs 
 * @param cellPricePs 
 * @param mcBitPricePs 
 * @param mcCellPricePs 
 */
@Serializable

data class BlockchainConfig18StoragePricesInner (

    @SerialName(value = "utime_since")
    val utimeSince: kotlin.Long,

    @SerialName(value = "bit_price_ps")
    val bitPricePs: kotlin.Long,

    @SerialName(value = "cell_price_ps")
    val cellPricePs: kotlin.Long,

    @SerialName(value = "mc_bit_price_ps")
    val mcBitPricePs: kotlin.Long,

    @SerialName(value = "mc_cell_price_ps")
    val mcCellPricePs: kotlin.Long

)

