/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.SizeLimitsConfig

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The size limits and some other characteristics of accounts and messages.
 *
 * @param sizeLimitsConfig 
 */
@Serializable

data class BlockchainConfig43 (

    @SerialName(value = "size_limits_config")
    val sizeLimitsConfig: SizeLimitsConfig

)

