/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The cost of filing complaints about incorrect operation of validators.
 *
 * @param deposit 
 * @param bitPrice 
 * @param cellPrice 
 */
@Serializable

data class BlockchainConfig13 (

    @SerialName(value = "deposit")
    val deposit: kotlin.Long,

    @SerialName(value = "bit_price")
    val bitPrice: kotlin.Long,

    @SerialName(value = "cell_price")
    val cellPrice: kotlin.Long

)

