/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The reward in nanoTons for block creation in the TON blockchain.
 *
 * @param validatorsElectedFor 
 * @param electionsStartBefore 
 * @param electionsEndBefore 
 * @param stakeHeldFor 
 */
@Serializable

data class BlockchainConfig15 (

    @SerialName(value = "validators_elected_for")
    val validatorsElectedFor: kotlin.Long,

    @SerialName(value = "elections_start_before")
    val electionsStartBefore: kotlin.Long,

    @SerialName(value = "elections_end_before")
    val electionsEndBefore: kotlin.Long,

    @SerialName(value = "stake_held_for")
    val stakeHeldFor: kotlin.Long

)

