/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.ComputeSkipReason

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param skipped 
 * @param skipReason 
 * @param success 
 * @param gasFees 
 * @param gasUsed 
 * @param vmSteps 
 * @param exitCode 
 * @param exitCodeDescription 
 */
@Serializable

data class ComputePhase (

    @SerialName(value = "skipped")
    val skipped: kotlin.Boolean,

    @Contextual @SerialName(value = "skip_reason")
    val skipReason: ComputeSkipReason? = null,

    @SerialName(value = "success")
    val success: kotlin.Boolean? = null,

    @SerialName(value = "gas_fees")
    val gasFees: kotlin.Long? = null,

    @SerialName(value = "gas_used")
    val gasUsed: kotlin.Long? = null,

    @SerialName(value = "vm_steps")
    val vmSteps: kotlin.Int? = null,

    @SerialName(value = "exit_code")
    val exitCode: kotlin.Int? = null,

    @SerialName(value = "exit_code_description")
    val exitCodeDescription: kotlin.String? = null

)

