/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * Values: noState,badState,noGas
 */
@Serializable
enum class ComputeSkipReason(val value: kotlin.String) {

    @SerialName(value = "cskip_no_state")
    noState("cskip_no_state"),

    @SerialName(value = "cskip_bad_state")
    badState("cskip_bad_state"),

    @SerialName(value = "cskip_no_gas")
    noGas("cskip_no_gas");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ComputeSkipReason) "$data" else null

        /**
         * Returns a valid [ComputeSkipReason] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ComputeSkipReason? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

