/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param minTotRounds 
 * @param maxTotRounds 
 * @param minWins 
 * @param maxLosses 
 * @param minStoreSec 
 * @param maxStoreSec 
 * @param bitPrice 
 * @param cellPrice 
 */
@Serializable

data class ConfigProposalSetup (

    @SerialName(value = "min_tot_rounds")
    val minTotRounds: kotlin.Int,

    @SerialName(value = "max_tot_rounds")
    val maxTotRounds: kotlin.Int,

    @SerialName(value = "min_wins")
    val minWins: kotlin.Int,

    @SerialName(value = "max_losses")
    val maxLosses: kotlin.Int,

    @SerialName(value = "min_store_sec")
    val minStoreSec: kotlin.Long,

    @SerialName(value = "max_store_sec")
    val maxStoreSec: kotlin.Long,

    @SerialName(value = "bit_price")
    val bitPrice: kotlin.Long,

    @SerialName(value = "cell_price")
    val cellPrice: kotlin.Long

)

