/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param feesCollected 
 * @param credit 
 */
@Serializable

data class CreditPhase (

    @SerialName(value = "fees_collected")
    val feesCollected: kotlin.Long,

    @SerialName(value = "credit")
    val credit: kotlin.Long

)

