/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.DecodedRawMessage

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param subwalletId 
 * @param validUntil 
 * @param seqno 
 * @param rawMessages 
 */
@Serializable

data class DecodedMessageExtInMsgDecodedWalletV3 (

    @SerialName(value = "subwallet_id")
    val subwalletId: kotlin.Long,

    @SerialName(value = "valid_until")
    val validUntil: kotlin.Long,

    @SerialName(value = "seqno")
    val seqno: kotlin.Long,

    @SerialName(value = "raw_messages")
    val rawMessages: kotlin.collections.List<DecodedRawMessage>

)

