/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param boc 
 * @param decodedOpName 
 * @param opCode 
 * @param decodedBody 
 */
@Serializable

data class DecodedRawMessageMessage (

    @SerialName(value = "boc")
    val boc: kotlin.String,

    @SerialName(value = "decoded_op_name")
    val decodedOpName: kotlin.String? = null,

    @SerialName(value = "op_code")
    val opCode: kotlin.String? = null,

    @Contextual @SerialName(value = "decoded_body")
    val decodedBody: kotlin.Any? = null

)

