/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.NftItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param expiringAt 
 * @param name 
 * @param dnsItem 
 */
@Serializable

data class DnsExpiringItemsInner (

    @SerialName(value = "expiring_at")
    val expiringAt: kotlin.Long,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "dns_item")
    val dnsItem: NftItem? = null

)

