/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.WalletDNS

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param sites 
 * @param wallet 
 * @param nextResolver 
 * @param storage tonstorage bag id
 */
@Serializable

data class DnsRecord (

    @SerialName(value = "sites")
    val sites: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "wallet")
    val wallet: WalletDNS? = null,

    @SerialName(value = "next_resolver")
    val nextResolver: kotlin.String? = null,

    /* tonstorage bag id */
    @SerialName(value = "storage")
    val storage: kotlin.String? = null

)

