/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.NftItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param expiringAt date of expiring. optional. not all domain in ton has expiration date
 * @param item 
 */
@Serializable

data class DomainInfo (

    @SerialName(value = "name")
    val name: kotlin.String,

    /* date of expiring. optional. not all domain in ton has expiration date */
    @SerialName(value = "expiring_at")
    val expiringAt: kotlin.Long? = null,

    @SerialName(value = "item")
    val item: NftItem? = null

)

