/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param domain 
 * @param contractAddress 
 * @param renewer 
 */
@Serializable

data class DomainRenewAction (

    @SerialName(value = "domain")
    val domain: kotlin.String,

    @SerialName(value = "contract_address")
    val contractAddress: kotlin.String,

    @SerialName(value = "renewer")
    val renewer: AccountAddress

)

