/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.EmulateMessageToWalletRequestParamsInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param boc 
 * @param params additional per account configuration
 */
@Serializable

data class EmulateMessageToWalletRequest (

    @SerialName(value = "boc")
    val boc: kotlin.String,

    /* additional per account configuration */
    @SerialName(value = "params")
    val params: kotlin.collections.List<EmulateMessageToWalletRequestParamsInner>? = null

)

