/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param encryptionType 
 * @param cipherText 
 */
@Serializable

data class EncryptedComment (

    @SerialName(value = "encryption_type")
    val encryptionType: kotlin.String,

    @SerialName(value = "cipher_text")
    val cipherText: kotlin.String

)

