/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param walletPublicKey hex encoded public key
 * @param boc 
 */
@Serializable

data class GaslessSendRequest (

    /* hex encoded public key */
    @SerialName(value = "wallet_public_key")
    val walletPublicKey: kotlin.String,

    @SerialName(value = "boc")
    val boc: kotlin.String

)

