/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.GaslessEstimateRequestMessagesInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param walletAddress 
 * @param walletPublicKey 
 * @param messages 
 */
@Serializable

data class GaslessEstimateRequest (

    @SerialName(value = "wallet_address")
    val walletAddress: kotlin.String,

    @SerialName(value = "wallet_public_key")
    val walletPublicKey: kotlin.String,

    @SerialName(value = "messages")
    val messages: kotlin.collections.List<GaslessEstimateRequestMessagesInner>

)

