/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param comment 
 * @param destination 
 */
@Serializable

data class GetInscriptionOpTemplate200Response (

    @SerialName(value = "comment")
    val comment: kotlin.String,

    @SerialName(value = "destination")
    val destination: kotlin.String

)

