/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.BlockRaw

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param mode 
 * @param headerProof 
 */
@Serializable

data class GetRawBlockchainBlockHeader200Response (

    @SerialName(value = "id")
    val id: BlockRaw,

    @SerialName(value = "mode")
    val mode: kotlin.Int,

    @SerialName(value = "header_proof")
    val headerProof: kotlin.String

)

