/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.BlockRaw

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param mode 
 * @param id 
 * @param stateProof 
 * @param configProof 
 */
@Serializable

data class GetRawConfig200Response (

    @SerialName(value = "mode")
    val mode: kotlin.Int,

    @SerialName(value = "id")
    val id: BlockRaw,

    @SerialName(value = "state_proof")
    val stateProof: kotlin.String,

    @SerialName(value = "config_proof")
    val configProof: kotlin.String

)

