/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param mode 
 * @param account 
 * @param lt 
 * @param hash 
 */
@Serializable

data class GetRawListBlockTransactions200ResponseIdsInner (

    @SerialName(value = "mode")
    val mode: kotlin.Int,

    @SerialName(value = "account")
    val account: kotlin.String? = null,

    @SerialName(value = "lt")
    val lt: kotlin.Long? = null,

    @SerialName(value = "hash")
    val hash: kotlin.String? = null

)

