/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.BlockRaw
import io.tonapi.models.GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignatures

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param toKeyBlock 
 * @param from 
 * @param to 
 * @param destProof 
 * @param configProof 
 * @param signatures 
 */
@Serializable

data class GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForward (

    @SerialName(value = "to_key_block")
    val toKeyBlock: kotlin.Boolean,

    @SerialName(value = "from")
    val from: BlockRaw,

    @SerialName(value = "to")
    val to: BlockRaw,

    @SerialName(value = "dest_proof")
    val destProof: kotlin.String,

    @SerialName(value = "config_proof")
    val configProof: kotlin.String,

    @SerialName(value = "signatures")
    val signatures: GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignatures

)

