/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.BlockRaw
import io.tonapi.models.GetRawBlockProof200ResponseStepsInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param complete 
 * @param from 
 * @param to 
 * @param steps 
 */
@Serializable

data class GetRawBlockProof200Response (

    @SerialName(value = "complete")
    val complete: kotlin.Boolean,

    @SerialName(value = "from")
    val from: BlockRaw,

    @SerialName(value = "to")
    val to: BlockRaw,

    @SerialName(value = "steps")
    val steps: kotlin.collections.List<GetRawBlockProof200ResponseStepsInner>

)

