/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.BlockRaw
import io.tonapi.models.InitStateRaw

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param last 
 * @param stateRootHash 
 * @param `init` 
 */
@Serializable

data class GetRawMasterchainInfo200Response (

    @SerialName(value = "last")
    val last: BlockRaw,

    @SerialName(value = "state_root_hash")
    val stateRootHash: kotlin.String,

    @SerialName(value = "init")
    val `init`: InitStateRaw

)

