/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.BlockRaw
import io.tonapi.models.GetRawShardBlockProof200ResponseLinksInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param masterchainId 
 * @param links 
 */
@Serializable

data class GetRawShardBlockProof200Response (

    @SerialName(value = "masterchain_id")
    val masterchainId: BlockRaw,

    @SerialName(value = "links")
    val links: kotlin.collections.List<GetRawShardBlockProof200ResponseLinksInner>

)

