/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkBack
import io.tonapi.models.GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForward

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param liteServerBlockLinkBack 
 * @param liteServerBlockLinkForward 
 */
@Serializable

data class GetRawBlockProof200ResponseStepsInner (

    @SerialName(value = "lite_server_block_link_back")
    val liteServerBlockLinkBack: GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkBack,

    @SerialName(value = "lite_server_block_link_forward")
    val liteServerBlockLinkForward: GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForward

)

