/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignaturesSignaturesInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param validatorSetHash 
 * @param catchainSeqno 
 * @param signatures 
 */
@Serializable

data class GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignatures (

    @SerialName(value = "validator_set_hash")
    val validatorSetHash: kotlin.Long,

    @SerialName(value = "catchain_seqno")
    val catchainSeqno: kotlin.Int,

    @SerialName(value = "signatures")
    val signatures: kotlin.collections.List<GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignaturesSignaturesInner>

)

