/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.BlockRaw

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param ids 
 * @param transactions 
 */
@Serializable

data class GetRawTransactions200Response (

    @SerialName(value = "ids")
    val ids: kotlin.collections.List<BlockRaw>,

    @SerialName(value = "transactions")
    val transactions: kotlin.String

)

