/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.PoolImplementation
import io.tonapi.models.PoolInfo

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param implementation 
 * @param pool 
 */
@Serializable

data class GetStakingPoolInfo200Response (

    @SerialName(value = "implementation")
    val implementation: PoolImplementation,

    @SerialName(value = "pool")
    val pool: PoolInfo

)

