/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param resolution 
 * @param url 
 */
@Serializable

data class ImagePreview (

    @SerialName(value = "resolution")
    val resolution: kotlin.String,

    @SerialName(value = "url")
    val url: kotlin.String

)

