/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param workchain 
 * @param rootHash 
 * @param fileHash 
 */
@Serializable

data class InitStateRaw (

    @SerialName(value = "workchain")
    val workchain: kotlin.Int,

    @SerialName(value = "root_hash")
    val rootHash: kotlin.String,

    @SerialName(value = "file_hash")
    val fileHash: kotlin.String

)

