/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param recipient 
 * @param amount amount in minimal particles
 * @param type 
 * @param ticker 
 * @param decimals 
 */
@Serializable

data class InscriptionMintAction (

    @SerialName(value = "recipient")
    val recipient: AccountAddress,

    /* amount in minimal particles */
    @SerialName(value = "amount")
    val amount: kotlin.String,

    @SerialName(value = "type")
    val type: InscriptionMintAction.Type,

    @SerialName(value = "ticker")
    val ticker: kotlin.String,

    @SerialName(value = "decimals")
    val decimals: kotlin.Int

) {

    /**
     * 
     *
     * Values: ton20,gram20
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "ton20") ton20("ton20"),
        @SerialName(value = "gram20") gram20("gram20");
    }
}

