/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param ticker 
 * @param balance 
 * @param decimals 
 */
@Serializable

data class InscriptionBalance (

    @SerialName(value = "type")
    val type: InscriptionBalance.Type,

    @SerialName(value = "ticker")
    val ticker: kotlin.String,

    @SerialName(value = "balance")
    val balance: kotlin.String,

    @SerialName(value = "decimals")
    val decimals: kotlin.Int

) {

    /**
     * 
     *
     * Values: ton20,gram20
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "ton20") ton20("ton20"),
        @SerialName(value = "gram20") gram20("gram20");
    }
}

