/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.JettonPreview

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param dex 
 * @param amountIn 
 * @param amountOut 
 * @param userWallet 
 * @param router 
 * @param tonIn 
 * @param tonOut 
 * @param jettonMasterIn 
 * @param jettonMasterOut 
 */
@Serializable

data class JettonSwapAction (

    @SerialName(value = "dex")
    val dex: JettonSwapAction.Dex,

    @SerialName(value = "amount_in")
    val amountIn: kotlin.String,

    @SerialName(value = "amount_out")
    val amountOut: kotlin.String,

    @SerialName(value = "user_wallet")
    val userWallet: AccountAddress,

    @SerialName(value = "router")
    val router: AccountAddress,

    @SerialName(value = "ton_in")
    val tonIn: kotlin.Long? = null,

    @SerialName(value = "ton_out")
    val tonOut: kotlin.Long? = null,

    @SerialName(value = "jetton_master_in")
    val jettonMasterIn: JettonPreview? = null,

    @SerialName(value = "jetton_master_out")
    val jettonMasterOut: JettonPreview? = null

) {

    /**
     * 
     *
     * Values: stonfi,dedust,megatonfi
     */
    @Serializable
    enum class Dex(val value: kotlin.String) {
        @SerialName(value = "stonfi") stonfi("stonfi"),
        @SerialName(value = "dedust") dedust("dedust"),
        @SerialName(value = "megatonfi") megatonfi("megatonfi");
    }
}

