/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.JettonPreview

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param quantity 
 * @param walletAddress 
 * @param jetton 
 */
@Serializable

data class JettonQuantity (

    @SerialName(value = "quantity")
    val quantity: kotlin.String,

    @SerialName(value = "wallet_address")
    val walletAddress: AccountAddress,

    @SerialName(value = "jetton")
    val jetton: JettonPreview

)

