/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param address 
 * @param name 
 * @param symbol 
 * @param decimals 
 * @param image 
 * @param description 
 * @param social 
 * @param websites 
 * @param catalogs 
 * @param customPayloadApiUri 
 */
@Serializable

data class JettonMetadata (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "symbol")
    val symbol: kotlin.String,

    @SerialName(value = "decimals")
    val decimals: kotlin.String,

    @SerialName(value = "image")
    val image: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "social")
    val social: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "websites")
    val websites: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "catalogs")
    val catalogs: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "custom_payload_api_uri")
    val customPayloadApiUri: kotlin.String? = null

)

