/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.EncryptedComment
import io.tonapi.models.JettonPreview
import io.tonapi.models.Refund

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param sendersWallet 
 * @param recipientsWallet 
 * @param amount amount in quanta of tokens
 * @param jetton 
 * @param sender 
 * @param recipient 
 * @param comment 
 * @param encryptedComment 
 * @param refund 
 */
@Serializable

data class JettonTransferAction (

    @SerialName(value = "senders_wallet")
    val sendersWallet: kotlin.String,

    @SerialName(value = "recipients_wallet")
    val recipientsWallet: kotlin.String,

    /* amount in quanta of tokens */
    @SerialName(value = "amount")
    val amount: kotlin.String,

    @SerialName(value = "jetton")
    val jetton: JettonPreview,

    @SerialName(value = "sender")
    val sender: AccountAddress? = null,

    @SerialName(value = "recipient")
    val recipient: AccountAddress? = null,

    @SerialName(value = "comment")
    val comment: kotlin.String? = null,

    @SerialName(value = "encrypted_comment")
    val encryptedComment: EncryptedComment? = null,

    @SerialName(value = "refund")
    val refund: Refund? = null

)

