/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param customPayload hex-encoded BoC
 * @param stateInit hex-encoded BoC
 */
@Serializable

data class JettonTransferPayload (

    /* hex-encoded BoC */
    @SerialName(value = "custom_payload")
    val customPayload: kotlin.String? = null,

    /* hex-encoded BoC */
    @SerialName(value = "state_init")
    val stateInit: kotlin.String? = null

)

