/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param market 
 * @param usdPrice 
 * @param lastDateUpdate 
 */
@Serializable

data class MarketTonRates (

    @SerialName(value = "market")
    val market: kotlin.String,

    @Contextual @SerialName(value = "usd_price")
    val usdPrice: java.math.BigDecimal,

    @SerialName(value = "last_date_update")
    val lastDateUpdate: kotlin.Long

)

