/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountEvent
import io.tonapi.models.Risk
import io.tonapi.models.Trace

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param trace 
 * @param risk 
 * @param event 
 */
@Serializable

data class MessageConsequences (

    @SerialName(value = "trace")
    val trace: Trace,

    @SerialName(value = "risk")
    val risk: Risk,

    @SerialName(value = "event")
    val event: AccountEvent

)

