/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.StateInit

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param msgType 
 * @param createdLt 
 * @param ihrDisabled 
 * @param bounce 
 * @param bounced 
 * @param `value` 
 * @param fwdFee 
 * @param ihrFee 
 * @param importFee 
 * @param createdAt 
 * @param hash 
 * @param destination 
 * @param source 
 * @param opCode 
 * @param `init` 
 * @param rawBody hex-encoded BoC with raw message body
 * @param decodedOpName 
 * @param decodedBody 
 */
@Serializable

data class Message (

    @SerialName(value = "msg_type")
    val msgType: Message.MsgType,

    @SerialName(value = "created_lt")
    val createdLt: kotlin.Long,

    @SerialName(value = "ihr_disabled")
    val ihrDisabled: kotlin.Boolean,

    @SerialName(value = "bounce")
    val bounce: kotlin.Boolean,

    @SerialName(value = "bounced")
    val bounced: kotlin.Boolean,

    @SerialName(value = "value")
    val `value`: kotlin.Long,

    @SerialName(value = "fwd_fee")
    val fwdFee: kotlin.Long,

    @SerialName(value = "ihr_fee")
    val ihrFee: kotlin.Long,

    @SerialName(value = "import_fee")
    val importFee: kotlin.Long,

    @SerialName(value = "created_at")
    val createdAt: kotlin.Long,

    @SerialName(value = "hash")
    val hash: kotlin.String,

    @SerialName(value = "destination")
    val destination: AccountAddress? = null,

    @SerialName(value = "source")
    val source: AccountAddress? = null,

    @SerialName(value = "op_code")
    val opCode: kotlin.String? = null,

    @SerialName(value = "init")
    val `init`: StateInit? = null,

    /* hex-encoded BoC with raw message body */
    @SerialName(value = "raw_body")
    val rawBody: kotlin.String? = null,

    @SerialName(value = "decoded_op_name")
    val decodedOpName: kotlin.String? = null,

    @Contextual @SerialName(value = "decoded_body")
    val decodedBody: kotlin.Any? = null

) {

    /**
     * 
     *
     * Values: intMsg,extInMsg,extOutMsg
     */
    @Serializable
    enum class MsgType(val value: kotlin.String) {
        @SerialName(value = "int_msg") intMsg("int_msg"),
        @SerialName(value = "ext_in_msg") extInMsg("ext_in_msg"),
        @SerialName(value = "ext_out_msg") extOutMsg("ext_out_msg");
    }
}

