/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.Risk

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param address 
 * @param orderSeqno 
 * @param threshold 
 * @param sentForExecution 
 * @param signers 
 * @param approvalsNum 
 * @param expirationDate 
 * @param risk 
 * @param creationDate 
 * @param signedBy 
 */
@Serializable

data class MultisigOrder (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "order_seqno")
    val orderSeqno: kotlin.Long,

    @SerialName(value = "threshold")
    val threshold: kotlin.Int,

    @SerialName(value = "sent_for_execution")
    val sentForExecution: kotlin.Boolean,

    @SerialName(value = "signers")
    val signers: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "approvals_num")
    val approvalsNum: kotlin.Int,

    @SerialName(value = "expiration_date")
    val expirationDate: kotlin.Long,

    @SerialName(value = "risk")
    val risk: Risk,

    @SerialName(value = "creation_date")
    val creationDate: kotlin.Long,

    @SerialName(value = "signed_by")
    val signedBy: kotlin.collections.List<kotlin.String>

)

