/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.ImagePreview

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param address 
 * @param nextItemIndex 
 * @param rawCollectionContent 
 * @param approvedBy 
 * @param owner 
 * @param metadata 
 * @param previews 
 */
@Serializable

data class NftCollection (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "next_item_index")
    val nextItemIndex: kotlin.Long,

    @SerialName(value = "raw_collection_content")
    val rawCollectionContent: kotlin.String,

    @SerialName(value = "approved_by")
    val approvedBy: kotlin.collections.List<NftCollection.ApprovedBy>,

    @SerialName(value = "owner")
    val owner: AccountAddress? = null,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "previews")
    val previews: kotlin.collections.List<ImagePreview>? = null

) {

    /**
     * 
     *
     * Values: getgems,tonkeeper,tonPeriodDiamonds
     */
    @Serializable
    enum class ApprovedBy(val value: kotlin.String) {
        @SerialName(value = "getgems") getgems("getgems"),
        @SerialName(value = "tonkeeper") tonkeeper("tonkeeper"),
        @SerialName(value = "ton.diamonds") tonPeriodDiamonds("ton.diamonds");
    }
}

