/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.EncryptedComment
import io.tonapi.models.Refund

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param nft 
 * @param sender 
 * @param recipient 
 * @param comment 
 * @param encryptedComment 
 * @param payload raw hex encoded payload
 * @param refund 
 */
@Serializable

data class NftItemTransferAction (

    @SerialName(value = "nft")
    val nft: kotlin.String,

    @SerialName(value = "sender")
    val sender: AccountAddress? = null,

    @SerialName(value = "recipient")
    val recipient: AccountAddress? = null,

    @SerialName(value = "comment")
    val comment: kotlin.String? = null,

    @SerialName(value = "encrypted_comment")
    val encryptedComment: EncryptedComment? = null,

    /* raw hex encoded payload */
    @SerialName(value = "payload")
    val payload: kotlin.String? = null,

    @SerialName(value = "refund")
    val refund: Refund? = null

)

