/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param origin 
 */
@Serializable

data class Refund (

    @SerialName(value = "type")
    val type: Refund.Type,

    @SerialName(value = "origin")
    val origin: kotlin.String

) {

    /**
     * 
     *
     * Values: dNSPeriodTon,dNSPeriodTg,getGems
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "DNS.ton") dNSPeriodTon("DNS.ton"),
        @SerialName(value = "DNS.tg") dNSPeriodTg("DNS.tg"),
        @SerialName(value = "GetGems") getGems("GetGems");
    }
}

