/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.Price

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param address 
 * @param market 
 * @param price 
 * @param owner 
 */
@Serializable

data class Sale (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "market")
    val market: AccountAddress,

    @SerialName(value = "price")
    val price: Price,

    @SerialName(value = "owner")
    val owner: AccountAddress? = null

)

