/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param boc 
 * @param batch 
 */
@Serializable

data class SendBlockchainMessageRequest (

    @SerialName(value = "boc")
    val boc: kotlin.String? = null,

    @SerialName(value = "batch")
    val batch: kotlin.collections.List<kotlin.String>? = null

)

