/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param address 
 * @param amount Number of nanocoins to send. Decimal string.
 * @param payload Raw one-cell BoC encoded in hex.
 * @param stateInit Raw once-cell BoC encoded in hex.
 */
@Serializable

data class SignRawMessage (

    @SerialName(value = "address")
    val address: kotlin.String,

    /* Number of nanocoins to send. Decimal string. */
    @SerialName(value = "amount")
    val amount: kotlin.String,

    /* Raw one-cell BoC encoded in hex. */
    @SerialName(value = "payload")
    val payload: kotlin.String? = null,

    /* Raw once-cell BoC encoded in hex. */
    @SerialName(value = "stateInit")
    val stateInit: kotlin.String? = null

)

