/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param maxMsgBits 
 * @param maxMsgCells 
 * @param maxLibraryCells 
 * @param maxVmDataDepth 
 * @param maxExtMsgSize 
 * @param maxExtMsgDepth 
 * @param maxAccStateCells 
 * @param maxAccStateBits 
 */
@Serializable

data class SizeLimitsConfig (

    @SerialName(value = "max_msg_bits")
    val maxMsgBits: kotlin.Long,

    @SerialName(value = "max_msg_cells")
    val maxMsgCells: kotlin.Long,

    @SerialName(value = "max_library_cells")
    val maxLibraryCells: kotlin.Long,

    @SerialName(value = "max_vm_data_depth")
    val maxVmDataDepth: kotlin.Int,

    @SerialName(value = "max_ext_msg_size")
    val maxExtMsgSize: kotlin.Long,

    @SerialName(value = "max_ext_msg_depth")
    val maxExtMsgDepth: kotlin.Int,

    @SerialName(value = "max_acc_state_cells")
    val maxAccStateCells: kotlin.Long? = null,

    @SerialName(value = "max_acc_state_bits")
    val maxAccStateBits: kotlin.Long? = null

)

