/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param boc 
 * @param interfaces 
 */
@Serializable

data class StateInit (

    @SerialName(value = "boc")
    val boc: kotlin.String,

    @SerialName(value = "interfaces")
    val interfaces: kotlin.collections.List<kotlin.String>

)

