/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccStatusChange

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param feesCollected 
 * @param statusChange 
 * @param feesDue 
 */
@Serializable

data class StoragePhase (

    @SerialName(value = "fees_collected")
    val feesCollected: kotlin.Long,

    @Contextual @SerialName(value = "status_change")
    val statusChange: AccStatusChange,

    @SerialName(value = "fees_due")
    val feesDue: kotlin.Long? = null

)

