/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param address 
 * @param walletAddress 
 * @param beneficiaryAddress 
 * @param amount 
 * @param period 
 * @param startTime 
 * @param timeout 
 * @param lastPaymentTime 
 * @param lastRequestTime 
 * @param subscriptionId 
 * @param failedAttempts 
 */
@Serializable

data class Subscription (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "wallet_address")
    val walletAddress: kotlin.String,

    @SerialName(value = "beneficiary_address")
    val beneficiaryAddress: kotlin.String,

    @SerialName(value = "amount")
    val amount: kotlin.Long,

    @SerialName(value = "period")
    val period: kotlin.Long,

    @SerialName(value = "start_time")
    val startTime: kotlin.Long,

    @SerialName(value = "timeout")
    val timeout: kotlin.Long,

    @SerialName(value = "last_payment_time")
    val lastPaymentTime: kotlin.Long,

    @SerialName(value = "last_request_time")
    val lastRequestTime: kotlin.Long,

    @SerialName(value = "subscription_id")
    val subscriptionId: kotlin.Long,

    @SerialName(value = "failed_attempts")
    val failedAttempts: kotlin.Int

)

