/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param prices 
 * @param diff24h 
 * @param diff7d 
 * @param diff30d 
 */
@Serializable

data class TokenRates (

    @Contextual @SerialName(value = "prices")
    val prices: kotlin.collections.Map<kotlin.String, java.math.BigDecimal>? = null,

    @SerialName(value = "diff_24h")
    val diff24h: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "diff_7d")
    val diff7d: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "diff_30d")
    val diff30d: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

)

