/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `value` 
 * @param lengthBytes 
 */
@Serializable

data class TonConnectProofRequestProofDomain (

    @SerialName(value = "value")
    val `value`: kotlin.String,

    @SerialName(value = "length_bytes")
    val lengthBytes: kotlin.Int? = null

)

