/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.Transaction

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param transaction 
 * @param interfaces 
 * @param children 
 * @param emulated 
 */
@Serializable

data class Trace (

    @SerialName(value = "transaction")
    val transaction: Transaction,

    @SerialName(value = "interfaces")
    val interfaces: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "children")
    val children: kotlin.collections.List<Trace>? = null,

    @SerialName(value = "emulated")
    val emulated: kotlin.Boolean? = null

)

