/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param cell 
 * @param slice 
 * @param num 
 * @param tuple 
 */
@Serializable

data class TvmStackRecord (

    @SerialName(value = "type")
    val type: TvmStackRecord.Type,

    @SerialName(value = "cell")
    val cell: kotlin.String? = null,

    @SerialName(value = "slice")
    val slice: kotlin.String? = null,

    @SerialName(value = "num")
    val num: kotlin.String? = null,

    @SerialName(value = "tuple")
    val tuple: kotlin.collections.List<TvmStackRecord>? = null

) {

    /**
     * 
     *
     * Values: cell,num,nan,`null`,tuple
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "cell") cell("cell"),
        @SerialName(value = "num") num("num"),
        @SerialName(value = "nan") nan("nan"),
        @SerialName(value = "null") `null`("null"),
        @SerialName(value = "tuple") tuple("tuple");
    }
}

