/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param publicKey 
 * @param weight 
 * @param adnlAddr 
 */
@Serializable

data class ValidatorsSetListInner (

    @SerialName(value = "public_key")
    val publicKey: kotlin.String,

    @SerialName(value = "weight")
    val weight: kotlin.Long,

    @SerialName(value = "adnl_addr")
    val adnlAddr: kotlin.String? = null

)

