/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param address 
 * @param adnlAddress 
 * @param stake 
 * @param maxFactor 
 */
@Serializable

data class Validator (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "adnl_address")
    val adnlAddress: kotlin.String,

    @SerialName(value = "stake")
    val stake: kotlin.Long,

    @SerialName(value = "max_factor")
    val maxFactor: kotlin.Long

)

