/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param address 
 * @param account 
 * @param isWallet 
 * @param hasMethodPubkey 
 * @param hasMethodSeqno 
 * @param names 
 */
@Serializable

data class WalletDNS (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "account")
    val account: AccountAddress,

    @SerialName(value = "is_wallet")
    val isWallet: kotlin.Boolean,

    @SerialName(value = "has_method_pubkey")
    val hasMethodPubkey: kotlin.Boolean,

    @SerialName(value = "has_method_seqno")
    val hasMethodSeqno: kotlin.Boolean,

    @SerialName(value = "names")
    val names: kotlin.collections.List<kotlin.String>

)

