/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.PoolImplementationType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * validator's participation in elections
 *
 * @param staker 
 * @param pool 
 * @param implementation 
 * @param amount 
 */
@Serializable

data class WithdrawStakeRequestAction (

    @SerialName(value = "staker")
    val staker: AccountAddress,

    @SerialName(value = "pool")
    val pool: AccountAddress,

    @Contextual @SerialName(value = "implementation")
    val implementation: PoolImplementationType,

    @SerialName(value = "amount")
    val amount: kotlin.Long? = null

)

