/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param balance 
 * @param reserved reserved amount in units (TON/USD)
 * @param units 
 */
@Serializable

data class Balance (

    @SerialName(value = "balance")
    val balance: kotlin.String,

    /* reserved amount in units (TON/USD) */
    @SerialName(value = "reserved")
    val reserved: kotlin.String,

    @SerialName(value = "units")
    val units: Balance.Units

) {

    /**
     * 
     *
     * Values: usd,ton
     */
    @Serializable
    enum class Units(val value: kotlin.String) {
        @SerialName(value = "usd") usd("usd"),
        @SerialName(value = "ton") ton("ton");
    }
}

