/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param amount 
 * @param currency 
 * @param comment 
 * @param reason 
 * @param destination 
 * @param relayerEventId 
 */
@Serializable

data class CreateCustomRefundRequest (

    @SerialName(value = "amount")
    val amount: kotlin.String,

    @SerialName(value = "currency")
    val currency: kotlin.String,

    @SerialName(value = "comment")
    val comment: kotlin.String,

    @SerialName(value = "reason")
    val reason: kotlin.String,

    @SerialName(value = "destination")
    val destination: kotlin.String,

    @SerialName(value = "relayer_event_id")
    val relayerEventId: kotlin.Int? = null

)

