/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param payload 
 * @param battery 
 */
@Serializable

data class EstimateGaslessCostRequest (

    @SerialName(value = "payload")
    val payload: kotlin.String,

    @SerialName(value = "battery")
    val battery: kotlin.Boolean? = true

)

