/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param promo 
 */
@Serializable

data class IosBatteryPurchaseRequestTransactionsInner (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "promo")
    val promo: kotlin.String? = null

)

