/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param msg 
 * @param code 
 */
@Serializable

data class IOSBatteryPurchaseStatusTransactionsInnerError (

    @SerialName(value = "msg")
    val msg: kotlin.String,

    @SerialName(value = "code")
    val code: IOSBatteryPurchaseStatusTransactionsInnerError.Code

) {

    /**
     * 
     *
     * Values: invalidMinusBundleMinusId,invalidMinusProductMinusId,userMinusNotMinusFound,purchaseMinusIsMinusAlreadyMinusUsed,temporaryMinusError,unknown
     */
    @Serializable
    enum class Code(val value: kotlin.String) {
        @SerialName(value = "invalid-bundle-id") invalidMinusBundleMinusId("invalid-bundle-id"),
        @SerialName(value = "invalid-product-id") invalidMinusProductMinusId("invalid-product-id"),
        @SerialName(value = "user-not-found") userMinusNotMinusFound("user-not-found"),
        @SerialName(value = "purchase-is-already-used") purchaseMinusIsMinusAlreadyMinusUsed("purchase-is-already-used"),
        @SerialName(value = "temporary-error") temporaryMinusError("temporary-error"),
        @SerialName(value = "unknown") unknown("unknown");
    }
}

