/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param msg 
 * @param code 
 */
@Serializable

data class PromoCodeBatteryPurchaseStatusError (

    @SerialName(value = "msg")
    val msg: kotlin.String,

    @SerialName(value = "code")
    val code: PromoCodeBatteryPurchaseStatusError.Code

) {

    /**
     * 
     *
     * Values: promoMinusCodeMinusNotMinusFound,promoMinusExceededMinusAttempts,temporaryMinusError
     */
    @Serializable
    enum class Code(val value: kotlin.String) {
        @SerialName(value = "promo-code-not-found") promoMinusCodeMinusNotMinusFound("promo-code-not-found"),
        @SerialName(value = "promo-exceeded-attempts") promoMinusExceededMinusAttempts("promo-exceeded-attempts"),
        @SerialName(value = "temporary-error") temporaryMinusError("temporary-error");
    }
}

