/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models

import io.batteryapi.models.PurchasesPurchasesInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param totalPurchases 
 * @param purchases 
 */
@Serializable

data class Purchases (

    @SerialName(value = "total_purchases")
    val totalPurchases: kotlin.Int,

    @SerialName(value = "purchases")
    val purchases: kotlin.collections.List<PurchasesPurchasesInner>

)

