/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param amount 
 * @param charges 
 */
@Serializable

data class PurchasesPurchasesInnerRefundInformationRefunded (

    @SerialName(value = "amount")
    val amount: kotlin.String,

    @SerialName(value = "charges")
    val charges: kotlin.Int

)

