/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models

import io.batteryapi.models.PurchasesPurchasesInnerRefundInformation

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userPurchaseId 
 * @param purchaseId 
 * @param type 
 * @param charges 
 * @param datetime 
 * @param promo 
 * @param forAccountId 
 * @param amount Amount describes the amount paid by the user for this purchase when we know it. For crypto purchases it is always set.
 * @param currency Currency is set when we know it. For crypto purchases it is always set.
 * @param refundInformation 
 */
@Serializable

data class PurchasesPurchasesInner (

    @SerialName(value = "user_purchase_id")
    @Deprecated(message = "This property is deprecated.")
    val userPurchaseId: kotlin.Int,

    @SerialName(value = "purchase_id")
    val purchaseId: kotlin.Int,

    @SerialName(value = "type")
    val type: PurchasesPurchasesInner.Type,

    @SerialName(value = "charges")
    val charges: kotlin.Int,

    @SerialName(value = "datetime")
    val datetime: kotlin.String,

    @SerialName(value = "promo")
    val promo: kotlin.String? = null,

    @SerialName(value = "for_account_id")
    val forAccountId: kotlin.String? = null,

    /* Amount describes the amount paid by the user for this purchase when we know it. For crypto purchases it is always set. */
    @SerialName(value = "amount")
    val amount: kotlin.String? = null,

    /* Currency is set when we know it. For crypto purchases it is always set. */
    @SerialName(value = "currency")
    val currency: kotlin.String? = null,

    @SerialName(value = "refund_information")
    val refundInformation: PurchasesPurchasesInnerRefundInformation? = null

) {

    /**
     * 
     *
     * Values: android,ios,promoMinusCode,crypto,gift,onMinusTheMinusWayMinusGift
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "android") android("android"),
        @SerialName(value = "ios") ios("ios"),
        @SerialName(value = "promo-code") promoMinusCode("promo-code"),
        @SerialName(value = "crypto") crypto("crypto"),
        @SerialName(value = "gift") gift("gift"),
        @SerialName(value = "on-the-way-gift") onMinusTheMinusWayMinusGift("on-the-way-gift");
    }
}

