/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userPurchaseId 
 * @param purchaseId 
 */
@Serializable

data class RequestRefundRequest (

    @SerialName(value = "user_purchase_id")
    @Deprecated(message = "This property is deprecated.")
    val userPurchaseId: kotlin.Int? = null,

    @SerialName(value = "purchase_id")
    val purchaseId: kotlin.Int? = null

)

