/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param paidAmount represents the amount of money paid by the user for this transaction.
 * @param status 
 * @param createdAt 
 */
@Serializable

data class TransactionsTransactionsInner (

    @SerialName(value = "id")
    val id: kotlin.String,

    /* represents the amount of money paid by the user for this transaction. */
    @SerialName(value = "paid_amount")
    val paidAmount: kotlin.String,

    @SerialName(value = "status")
    val status: TransactionsTransactionsInner.Status,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String

) {

    /**
     * 
     *
     * Values: pending,completed,failed
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "pending") pending("pending"),
        @SerialName(value = "completed") completed("completed"),
        @SerialName(value = "failed") failed("failed");
    }
}

